/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
static yyconst short int yy_accept[265] =
    {   0,
        0,    0,    0,    0,   26,   18,   18,   18,   18,   18,
        1,   18,   18,   24,   24,    1,   24,   24,   24,   24,
       24,   24,    0,    0,    0,    0,    0,    0,    0,    9,
        0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    1,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   23,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   20,   19,    0,    0,    0,   22,
        0,    0,   15,    0,    0,    0,    0,    8,    0,    0,
        0,   14,    3,    0,   12,    0,    0,    0,    0,    0,
        0,    0,   12,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    2,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        7,    0,    0,    0,    0,    0,    0,    0,    7,   21,
        0,    0,    4,    0,   16,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   17,    0,    0,
        6,    4,    4,    0,    0,   11,    0,    6,    0,   11,
        4,    0,    0,   13,    0,   13,    5,    0,    5,    0,
        0,    0,   10,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    1,    4,    1,    1,    5,
        6,    1,    1,    1,    7,    8,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
       10,    1,    1,    1,    1,    1,   11,   12,    1,    1,
        1,    1,   13,    1,    1,    1,   14,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,    1,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   33,   34,   35,    1,
       36,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[37] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[273] =
    {   0,
        0,   30,   58,   86,  577,  573,  578,    9,    4,    7,
       11,    6,   23,  578,   13,   36,  550,  546,  550,  549,
      543,    5,  567,    8,   44,   14,   20,   19,   18,  578,
       48,   50,   66,   57,   51,   61,   70,   49,   71,  567,
       77,   85,  540,  547,  541,  538,  530,  531,  532,   68,
       79,   84,   73,   95,   98,  116,  105,  117,  118,   62,
      107,  123,   99,  111,  143,  530,  537,  534,  539,  538,
      112,  528,  132,  126,  128,  136,  153,  156,  159,  162,
      164,  167,  171,  165,  166,  148,  172,  176,  157,  181,
      185,  197,  536,  529,  578,  521,  520,  521,  527,  528,

      524,  187,  179,  189,  198,  200,  202,  206,  208,  210,
      217,  219,  220,  212,  214,  221,  227,  229,  235,  237,
      239,  249,  244,  518,  521,  517,  516,  528,  515,  525,
      521,  119,  240,  246,  250,  254,  258,  266,  271,  274,
      276,  277,  252,  263,  279,  267,  281,  285,  283,  287,
      290,  296,  303,  524,  578,  578,  502,  518,  519,  578,
      291,  298,  532,  305,  309,  311,  314,  578,  319,  325,
      327,  328,  531,  316,  530,  322,  332,  329,  336,  342,
      344,  500,  578,  496,  502,  337,  334,  339,  348,  356,
      360,  362,  370,  364,  349,  365,  353,  526,  377,  380,

      382,  506,  504,  501,  522,  371,  374,  384,  387,  398,
      402,  404,  406,  521,  399,  393,  413,  416,  420,  578,
      505,  494,  407,  425,  518,  427,  430,  432,  437,  440,
      417,  423,  428,  447,  450,  473,  472,  498,  454,  458,
      461,  483,  462,  451,  444,  438,  469,  471,  386,  578,
      473,  477,  474,  395,  485,  578,  487,  478,  497,  480,
      464,  475,  306,  578,  508,  510,  261,  512,    0,  514,
      516,  518
    } ;

static yyconst short int yy_def[273] =
    {   0,
      265,  265,  266,  266,  264,  267,  264,  267,  268,  269,
      267,  267,  267,  264,  270,  264,  264,  264,  264,  264,
      264,  264,  267,  267,  267,  267,  267,  267,  268,  264,
      271,  269,  269,  269,  267,  267,  267,  267,  267,  270,
      272,  264,  264,  264,  264,  264,  264,  264,  264,  267,
      267,  267,  267,  268,  271,  271,  271,  269,  269,  267,
      267,  267,  267,  272,  272,  264,  264,  264,  264,  264,
      264,  264,  267,  267,  267,  267,  268,  271,  271,  271,
      271,  269,  269,  267,  267,  267,  267,  267,  267,  272,
      272,  272,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  267,  267,  267,  267,  268,  271,  271,  271,  271,
      271,  269,  269,  267,  267,  267,  267,  267,  267,  272,
      272,  272,  272,  264,  264,  264,  264,  264,  264,  264,
      264,  267,  267,  267,  267,  268,  271,  271,  271,  271,
      271,  269,  269,  267,  267,  267,  267,  267,  267,  272,
      272,  272,  272,  264,  264,  264,  264,  264,  264,  264,
      267,  267,  267,  267,  268,  271,  271,  264,  271,  271,
      269,  269,  267,  267,  267,  267,  267,  267,  272,  272,
      272,  264,  264,  264,  264,  267,  267,  267,  268,  271,
      271,  271,  271,  269,  267,  267,  267,  267,  272,  272,

      272,  264,  264,  264,  267,  267,  267,  268,  271,  271,
      271,  271,  269,  267,  267,  267,  272,  272,  272,  264,
      264,  264,  267,  267,  267,  268,  271,  271,  271,  269,
      267,  267,  267,  272,  272,  264,  264,  267,  268,  271,
      271,  271,  269,  267,  267,  267,  272,  272,  264,  264,
      268,  271,  267,  267,  272,  264,  271,  267,  272,  267,
      267,  267,  267,    0,  264,  264,  264,  264,  264,  264,
      264,  264
    } ;

static yyconst short int yy_nxt[615] =
    {   0,
       32,    7,    8,    9,   10,   30,   31,   11,   24,   33,
       24,   24,   34,   24,   30,   41,   24,   35,   35,   30,
       54,   24,   24,   48,   36,   24,   12,   25,   25,   35,
       13,    7,    8,    9,   10,   26,   49,   11,   27,   37,
       28,   38,   42,   42,   39,   51,   24,   52,   53,   30,
       56,   24,   33,   24,   42,   34,   12,   35,   35,   59,
       13,   15,   34,   24,   24,   16,   50,   57,   33,   35,
       24,   34,   24,   24,   17,   24,   18,   19,   30,   65,
       62,   24,   20,   21,   61,   58,   24,   76,   22,   15,
       84,   42,   42,   16,   73,   60,   30,   54,   63,   30,

       56,   24,   17,   42,   18,   19,   30,   56,   74,   24,
       20,   21,   30,   65,   77,   75,   22,   30,   56,   33,
       33,   24,   34,   34,   78,   24,   79,   81,   24,   80,
       24,   85,   98,   89,   24,   57,   99,   58,   24,   82,
      103,  100,  104,   86,   30,   65,  161,   87,   83,  102,
       24,   90,   88,   91,   30,   54,   92,   30,   56,   24,
       30,   56,  105,   30,   56,   30,   56,   24,   24,   33,
      107,  109,   34,   33,   24,  106,   34,  116,   24,  114,
      110,   24,   30,   65,  115,  119,   30,   65,  108,   24,
      111,   24,  113,  112,  117,  120,  118,  122,   30,   65,

       24,   30,   54,   30,   56,  133,  132,   30,   56,   30,
       56,   30,   56,  121,   24,  123,   24,  139,   30,   56,
      134,   33,   33,   24,   34,   34,  136,  137,  135,   24,
      138,   24,  140,  145,  141,  146,  142,   24,   30,   65,
       30,   65,   24,  144,  148,   30,   65,  143,   24,  149,
       30,   65,   24,  147,   33,   30,   54,   34,  152,   30,
       56,   23,  150,  151,  163,   24,  153,   30,   56,   24,
      162,  165,  168,   56,  164,   30,   56,   30,   56,   33,
      166,   24,   34,   24,  173,   24,  172,   24,   30,   65,
      167,   30,   65,   24,  169,  170,  171,  168,   65,  176,

       24,  177,  175,  178,   30,   65,  174,   24,   24,  179,
       30,   54,   30,   56,  180,   30,   56,  186,   24,  188,
       30,   56,  187,  181,   24,  191,   30,   56,  189,   33,
       33,   24,   34,   34,   24,  190,   24,   30,   65,   24,
      192,   24,  195,   30,   65,   30,   65,  198,  206,   30,
       54,   24,  193,  200,  194,   24,  196,   30,   56,  197,
      199,   30,   56,   30,   56,  201,   33,   24,  205,   34,
      207,   30,   56,   24,  210,  208,   24,  216,   30,   65,
      214,   30,   65,   30,   65,   30,   54,  215,   30,   56,
      213,  209,  225,  211,  218,   24,  212,   24,  227,   30,

       56,   24,  224,   30,   56,   30,   56,  256,   33,   24,
      226,   34,  217,  219,   30,   65,  232,   30,   65,   24,
      233,   30,   65,  228,  234,   24,   25,   24,   30,   54,
       24,   30,   56,   30,   56,  229,   25,  230,   30,  242,
       24,  235,  243,  238,  240,   34,   24,  244,   30,   65,
      241,   30,   65,   24,  245,   30,  251,  246,  239,   30,
       56,  247,   30,   56,   33,  254,   24,   34,  248,  253,
       30,   65,   30,   65,   30,   54,   24,   24,   30,   56,
       24,   58,   24,  252,   30,   56,   30,   65,   30,   56,
      262,   78,   77,   79,  255,  257,   80,  260,   30,   65,

       24,  250,   57,  259,  249,  258,  263,  261,    6,    6,
       14,   14,   29,   29,   40,   40,   55,   55,   64,   64,
       24,  237,  236,  231,  223,  222,  221,  220,   24,  204,
      203,  202,   24,   24,   24,  185,  184,  183,  182,  160,
      159,  158,  157,  156,  155,   95,  154,  131,  130,  129,
      128,  127,  126,  125,  124,  101,   97,   96,   95,   94,
       93,   72,   71,   70,   69,   68,   67,   66,   30,   24,
       47,   46,   45,   44,   43,   24,  264,    5,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264
    } ;

static yyconst short int yy_chk[615] =
    {   0,
      269,    1,    1,    1,    1,    9,    9,    1,   12,   10,
       24,    8,   10,   11,   15,   15,   26,   11,   11,   29,
       29,   28,   27,   22,   12,   13,    1,   24,    8,   11,
        1,    2,    2,    2,    2,    8,   22,    2,    8,   13,
        8,   13,   16,   16,   13,   26,   25,   27,   28,   31,
       31,   38,   32,   35,   16,   32,    2,   35,   35,   34,
        2,    3,   34,   36,   60,    3,   25,   31,   33,   35,
       50,   33,   37,   39,    3,   53,    3,    3,   41,   41,
       38,   51,    3,    3,   37,   33,   52,   53,    3,    4,
       60,   42,   42,    4,   50,   36,   54,   54,   39,   55,

       55,   63,    4,   42,    4,    4,   57,   57,   51,   61,
        4,    4,   64,   64,   54,   52,    4,   56,   56,   58,
       59,  132,   58,   59,   56,   62,   56,   57,   74,   56,
       75,   61,   71,   63,   73,   56,   71,   59,   76,   58,
       74,   71,   75,   62,   65,   65,  132,   62,   59,   73,
       86,   65,   62,   65,   77,   77,   65,   78,   78,   89,
       79,   79,   76,   80,   80,   81,   81,   84,   85,   82,
       78,   79,   82,   83,   87,   77,   83,   86,   88,   84,
       80,  103,   90,   90,   85,   89,   91,   91,   78,  102,
       81,  104,   83,   82,   87,   90,   88,   91,   92,   92,

      105,  106,  106,  107,  107,  103,  102,  108,  108,  109,
      109,  110,  110,   90,  114,   92,  115,  109,  111,  111,
      104,  112,  113,  116,  112,  113,  106,  107,  105,  117,
      108,  118,  110,  115,  111,  116,  112,  119,  120,  120,
      121,  121,  133,  114,  118,  123,  123,  113,  134,  119,
      122,  122,  135,  117,  143,  136,  136,  143,  122,  137,
      137,  267,  120,  121,  134,  144,  123,  138,  138,  146,
      133,  136,  139,  139,  135,  140,  140,  141,  141,  142,
      137,  145,  142,  147,  144,  149,  143,  148,  150,  150,
      138,  151,  151,  161,  140,  141,  142,  152,  152,  147,

      162,  148,  146,  149,  153,  153,  145,  164,  263,  150,
      165,  165,  166,  166,  151,  167,  167,  161,  174,  164,
      169,  169,  162,  153,  176,  167,  170,  170,  165,  171,
      172,  178,  171,  172,  177,  166,  187,  179,  179,  186,
      169,  188,  174,  180,  180,  181,  181,  178,  187,  189,
      189,  195,  170,  180,  171,  197,  176,  190,  190,  177,
      179,  191,  191,  192,  192,  181,  194,  196,  186,  194,
      188,  193,  193,  206,  191,  189,  207,  197,  199,  199,
      195,  200,  200,  201,  201,  208,  208,  196,  209,  209,
      194,  190,  207,  192,  200,  216,  193,  254,  209,  210,

      210,  215,  206,  211,  211,  212,  212,  249,  213,  223,
      208,  213,  199,  201,  217,  217,  215,  218,  218,  231,
      216,  219,  219,  210,  217,  232,  223,  224,  226,  226,
      233,  227,  227,  228,  228,  212,  231,  213,  229,  229,
      246,  218,  230,  224,  227,  230,  245,  231,  234,  234,
      228,  235,  235,  244,  232,  239,  239,  233,  226,  240,
      240,  234,  241,  241,  243,  245,  261,  243,  235,  244,
      247,  247,  248,  248,  251,  251,  253,  262,  252,  252,
      258,  243,  260,  240,  242,  242,  255,  255,  257,  257,
      261,  242,  251,  242,  247,  252,  242,  258,  259,  259,

      238,  237,  242,  255,  236,  253,  262,  260,  265,  265,
      266,  266,  268,  268,  270,  270,  271,  271,  272,  272,
      225,  222,  221,  214,  205,  204,  203,  202,  198,  185,
      184,  182,  175,  173,  163,  159,  158,  157,  154,  131,
      130,  129,  128,  127,  126,  125,  124,  101,  100,   99,
       98,   97,   96,   94,   93,   72,   70,   69,   68,   67,
       66,   49,   48,   47,   46,   45,   44,   43,   40,   23,
       21,   20,   19,   18,   17,    6,    5,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "makeedit.l"
#define INITIAL 0
#line 2 "makeedit.l"
/*
   makeedit.l : This file is part of pstoedit
   Simple parser to parse the intermediate flat PostScript and call the backend
   output routines.

   Copyright (C) 1993,1994,1995 Wolfgang Glunz, Wolfgang.Glunz@zfe.siemens.de

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

*/
// #include <stdio.h>
#include <iostream.h>
#include <fstream.h>
#include <string.h>

#include "config.h"
#include "drvTGIF.h"
#include "drvMIF.h"
#include "drvFIG.h"

#ifdef WITHPDF
#include "drvPDF.h"
#endif

#ifdef WITHCGM
#include "drvCGM.h"
#endif


drvbase * outputdriver;

static float  origx, origy;
static char   *start_of_text;
static char   *end_of_text;
static float  number;

#define READPATH 1

#line 635 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 52 "makeedit.l"

#line 784 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 265 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 578 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "makeedit.l"
{ 
			 if (!sscanf(yytext,"%f",&number)) {
			   cerr << "sscanf failed: " << yytext << endl;
			 }; 
			 /* printf(" adding  %f\n",number); */
			 outputdriver->addNumber(number * outputdriver->get_scale());
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "makeedit.l"
{ 
			if (!outputdriver->page_empty) {
				outputdriver->close_page();
			}
			outputdriver->page_empty = 1;
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "makeedit.l"
{ 
			BEGIN(READPATH); 
			outputdriver->currentSegment().currenttype=drvbase::polyline; /* init */
			outputdriver->newSegment();
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 71 "makeedit.l"
{
			/* /Helvetica findfont 14 scalefont setfont */
			start_of_text = strchr (yytext,(int)'/') + 1 ;
			end_of_text = strchr (yytext,(int)' ') ;
			*end_of_text = (char) 0;
			char * ATposition = 0; // look for a @ in name. This is inserted by groff.
					       // Replace @ with end-of-string
			// This is a temporary fix to the more general problem of font encodings
			if ((ATposition = strchr(yytext,(int)'@')) != 0 ) {
				*ATposition = (char) 0;
			}
			outputdriver->setCurrentFontName(start_of_text);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "makeedit.l"
{ 
			/* fprintf(stderr,"%s\n",yytext);  */
			start_of_text = yytext+2;
			end_of_text =  strrchr (yytext,(int)' ') ;
			*end_of_text = (char) 0;
			outputdriver->setCurrentFontFamilyName(start_of_text);
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 91 "makeedit.l"
{ 
			/* fprintf(stderr,"%s\n",yytext);  */
			start_of_text = yytext+2;
			end_of_text =  strrchr (yytext,(int)' ') ;
			*end_of_text = (char) 0;
			outputdriver->setCurrentFontFullName(start_of_text);
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 98 "makeedit.l"
{ 
			/* fprintf(stderr,"%s\n",yytext);  */
			start_of_text = yytext+2;
			end_of_text =  strrchr (yytext,(int)' ') ;
			*end_of_text = (char) 0;
			outputdriver->setCurrentFontWeight(start_of_text);
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "makeedit.l"
{
				cerr << yytext;
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 108 "makeedit.l"
{ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "makeedit.l"
{
			outputdriver->setCurrentFontSize(number * outputdriver->get_scale());
			outputdriver->pop(); 
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 113 "makeedit.l"
{
			float B = outputdriver->pop() / outputdriver->get_scale();
			float G = outputdriver->pop() / outputdriver->get_scale();
			float R = outputdriver->pop() / outputdriver->get_scale();
			/* printf("%s %f %f %f\n","setting RGB to ",R,G,B); */
			outputdriver->setRGB(R,G,B);
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 120 "makeedit.l"
{
			outputdriver->setGrayLevel(number);
			outputdriver->pop();
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "makeedit.l"
{
			outputdriver->setcurrentLineWidth(number * outputdriver->get_scale() );
			outputdriver->pop(); 
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 128 "makeedit.l"
{ 
			start_of_text = strchr (yytext,(int)'(') + 1 ;
			end_of_text = strrchr (yytext,(int)')') ;
			*end_of_text = (char) 0;
			outputdriver->showText(start_of_text);
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "makeedit.l"
{
			outputdriver->setCurrentFontAngle(number);
			outputdriver->pop();
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 138 "makeedit.l"
{
			/* Because this is in the preamble, only pop 
			   this has put something on the stack. */
			if (outputdriver->nrOfPointsInSegment(outputdriver->currentSegment()) >= 2)
				{ outputdriver->pop(); outputdriver->pop(); }
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 144 "makeedit.l"
{
			/* Because this is in the preamble, only pop 
			   this has put something on the stack. */
			if (outputdriver->nrOfPointsInSegment(outputdriver->currentSegment()) >= 2)
				{ outputdriver->pop(); outputdriver->pop(); }
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 150 "makeedit.l"
{ /* ignore any other stuff */ }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 151 "makeedit.l"
{ 
		    	if (outputdriver->nrOfPointsInSegment(outputdriver->currentSegment()) >= 2) {
				origx = outputdriver->numbers[outputdriver->currentSegment().end-2];
				origy = outputdriver->numbers[outputdriver->currentSegment().end-1];
				// save coordinates for possible closepath
			    	if (outputdriver->nrOfPointsInSegment(outputdriver->currentSegment()) > 2) {
			       		/* this is an intermediate moveto */
					/* take away the last point */
				        outputdriver->pop(); 
				        outputdriver->pop(); 

				/*	outputdriver->showSegments(outputdriver->noFillValue); */
			 		outputdriver->newSegment();
					/* start a new segment */
					outputdriver->addNumber(origx);
					outputdriver->addNumber(origy);
		     		}
		     	}
		   }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 170 "makeedit.l"
{ }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 171 "makeedit.l"
{
			 outputdriver->addNumber(origx);
			 outputdriver->addNumber(origy);
			 outputdriver->currentSegment().currenttype=drvbase::polygon;
			 outputdriver->newSegment();
			 /* show is done by next stroke, fill or moveto */
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 178 "makeedit.l"
{ 
			 BEGIN(INITIAL);
			 outputdriver->showSegments(outputdriver->noFillValue);
                       	};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 182 "makeedit.l"
{ 
			 BEGIN(INITIAL);
			 /* don't show border with fill */
			 outputdriver->setcurrentLineWidth(0);  
			 outputdriver->showSegments(outputdriver->FillValue); 
                       	};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 188 "makeedit.l"
{}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 189 "makeedit.l"
ECHO;
	YY_BREAK
#line 1104 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(READPATH):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 265 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 265 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 264);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 189 "makeedit.l"


enum driverType { unknown, tgif, mif, fig, cgm, pdf };

int main(int argc, char* const * argv)
// g++ wants 'char * const *' here, but that's a problem in getopts prototype
// Suns SparcCompiler expects 'const char* const *' for getopt
{
    int     c;
    char    *nameOfOutputFile = 0;
    driverType driver = unknown;

//    extern int optind;
//   extern int opterr;
#ifdef __GNUG__
    extern char *optarg;
#endif
    float  magnification = 1.0;
    while ((c = getopt(argc, argv, "m:f:o:")) != EOF)
	switch (c) {
	case 'm':
	    if (!sscanf(optarg, "%f", &magnification)) {
		perror("scanning magnification");
	    }
	    break;
	case 'f':
	    if (*optarg == 't')
		driver = tgif;
	    if (*optarg == 'm')
		driver = mif;
	    if (*optarg == 'f')
		driver = fig;
	    if (*optarg == 'c')
		driver = cgm;
	    if (*optarg == 'p')
		driver = pdf;
	    break;
	case 'o':
	    {
		const int filenamelen = strlen(optarg);
		nameOfOutputFile = new char[filenamelen+1];
		strcpy(nameOfOutputFile,optarg);
		break;
	    }
	case '?':
	    cerr << "Unknown Option to makeoutput" << endl;
	    break;
	}
    if (driver == unknown) {
	cerr << "No backend specified" << endl;
	delete nameOfOutputFile;
	exit(1);
    } else {
	if (!nameOfOutputFile) {
		cerr << "No output file specified" << endl;
		exit(1);
	}
	ofstream outFile;
	outFile.open(nameOfOutputFile);
	if (outFile.fail() ) {
		cerr << "Could not open file " << nameOfOutputFile << " for output" << endl;
		delete nameOfOutputFile;
		exit(1);
	}
	switch (driver) {
	case unknown:
		// cannot happen
		break;
	case tgif:
		outputdriver = new drvTGIF(outFile,magnification);
		break;
	case mif:
		outputdriver = new drvMIF(outFile,magnification);
		break;
	case fig:
		outputdriver = new drvFIG(outFile,magnification);
		break;
	case cgm:
#ifdef WITHCGM
		outputdriver = new drvCGM(outFile,magnification);
#endif
		break;
	case pdf:
#ifdef WITHPDF
		outputdriver = new drvPDF(outFile,magnification);
#endif
		break;
	default:
		break;
	}
 	outputdriver->setGrayLevel((float) 0.0);
        outputdriver->print_header();
        yylex();
        outputdriver->print_trailer();
	delete outputdriver;
    }
    return 0;
}
