.TH PSTOEDITQTGUI 1 "April 2026" "pstoedit" "User Commands"
.SH NAME
PstoeditQtGui \- graphical frontend for pstoedit
.SH SYNOPSIS
.B PstoeditQtGui
.SH DESCRIPTION
.B PstoeditQtGui
is a Qt-based graphical user interface for
.BR pstoedit (1),
a tool for converting PostScript and PDF files to other vector graphics formats.
.SH SEE ALSO
.BR pstoedit (1)
